LAHI/LAHI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('teacher/', include('teachers.urls')),
    path('student/', include('students.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LAHI/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
	path('', views.homepage, name='homepage'),
	path('download/<str:filename>', views.download, name='download'),
	path('logout', views.logout_view, name='logout')
]

LAHI/students/urls.py
from django.urls import path
from . import views 

app_name = 'students'

urlpatterns = [
	path('login', views.student_login, name='student_login'),
	path('materials', views.materials, name='materials'),
	path('dashboard', views.dashboard, name='dashboard'),
	path('agenda', views.agenda, name='agenda'),
	path('feedback',views.feedback, name='feedback'),
	path('content',views.content, name='content'),
]

LAHI/teachers/urls.py
from django.urls import path
from . import views 

app_name = 'teachers'

urlpatterns = [
	path('login', views.teacher_login, name='teacher_login'),
	path('uploadfiles', views.upload_files, name='upload_files'),
	path('materials', views.materials, name='materials'),
    path('createstudent', views.create_student, name='create_student'),
	path('dashboard', views.dashboard, name='dashboard'),
	path('agenda', views.agenda, name='agenda'),
]

LAHI/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>LMAI</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{%static 'css/style.css' %}"> 
  <link rel="stylesheet" href="{%static 'css/class.css' %}"> 
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

  
</head>
  {% include 'navbar.html' %}
<body>

  <div class="container">
    {% block content %}
  
    {% endblock %}
  </div>


  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</body>
</html>

LAHI/templates/navbar.html
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">LMAI</a>
      </div>
      
      <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
        <li><a href="#"><div class="flex"><form action="{% url 'main:logout' %}" method="post">{% csrf_token %}<button type="submit">Logout</button></form></div></a></li>
      {% else %}
        <li><a href="{%url 'students:student_login' %}"><span class="glyphicon glyphicon-log-in"></span>Student Login</a></li>
        <li><a href="{% url 'teachers:teacher_login' %}"><span class="glyphicon glyphicon-log-in"></span>Faculty Login</a></li>
      {% endif %}
      </ul>
    </div>
</nav>