LAHI/LAHI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('teacher/', include('teachers.urls')),
    path('student/', include('students.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LAHI/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
	path('', views.homepage, name='homepage'),
	path('download/<str:filename>', views.download, name='download'),
	path('logout', views.logout_view, name='logout')
]

LAHI/teachers/urls.py
from django.urls import path
from . import views 

app_name = 'teachers'

urlpatterns = [
	path('login', views.teacher_login, name='teacher_login'),
	path('uploadfiles', views.upload_files, name='upload_files'),
	path('materials', views.materials, name='materials'),
    path('createstudent', views.create_student, name='create_student'),
	path('dashboard', views.dashboard, name='dashboard'),
	path('agenda', views.agenda, name='agenda'),
]

LAHI/teachers/models.py
from django.db import models
from main.models import *
from django import forms
from django.contrib.auth.models import User


class Student(models.Model):
    user = models.OneToOneField(User, default=None, on_delete=models.CASCADE)
    roll_no = models.IntegerField(unique=True)
    phone = models.CharField(max_length=15, default=None, blank=False, null=False)
    std = models.ForeignKey(Standard, default=None, on_delete=models.SET_DEFAULT)

    def __str__(self):
        return str(self.user)

LAHI/teachers/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User 
from main.models import MediaFile
from .models import Student


class NewStudentForm(forms.ModelForm):
	# email = forms.EmailField(required=True)
    pass
	# class Meta:
	# 	model = Student
	# 	fields = ['name', 'roll_no', 'phone', 'std']

	# def save(self, commit=True):
	# 	user = super(NewStudentForm, self).save(commit=False)
	# 	user.email = self.cleaned_data['email']
	# 	if commit:
	# 		user.save()
	# 	return user

class MediaForm(forms.ModelForm):
    class Meta:
        model= MediaFile
        fields= ["std", "subject", "file_type", "media"]

LAHI/teachers/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.http import HttpResponse
from .forms import *
from main.models import MediaFile, Standard

def teacher_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            # if 'next' in request.POST:
            #     return redirect(request.POST.get('next'))
            # else:
            return redirect('teachers:dashboard')
                
    else:
        form = AuthenticationForm()
    return render(request, 'teachers/login.html', { 'form': form })
    # return HttpResponse("teacher login")

def upload_files(request):
    if request.method == 'POST':
        form = MediaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponse('File uploaded successfuly')
    else:
        form = MediaForm()
    return render(request, 'teachers/uploadfiles.html', {'form':form})

def materials(request):
    media = MediaFile.objects.all()
    return render(request, 'teachers/content.html', {'media':media})

def create_student(request):
    # return HttpResponse("hello there")
    if request.method == 'POST':
        if request.POST['pass'] == request.POST['passagain']:
            try:
                user = User.objects.get(username=request.POST['uname'])
                roll_no = Student.objects.get(roll_no=request.POST['roll_no'])
                return render(request, 'teachers/createstudent.html', {'error':"User already exist!"})
            except User.DoesNotExist or Student.DoesNotExist:
                roll_no = request.POST['rollno']
                phone = request.POST['phone']
                std = Standard.objects.get(standard=request.POST['std'])
                user = User.objects.create_user(username=request.POST['uname'], password=request.POST['pass'])
                student = Student(user=user, roll_no=roll_no, phone=phone, std=std)
                student.save()
                return HttpResponse("user created")
        else:
            return render(request, 'teachers/createstudent.html', {'error':"Password doesn't match"})
    
    return render(request, 'teachers/createstudent.html')
        # return HttpResponse("create a new user")

def dashboard(request):
    return render(request, 'teachers/dashboard.html')

def agenda(request):
    return render(request, 'teachers/agenda.html')

LAHI/teachers/templates/teachers/PageOfVideos.html
{% extends 'base.html' %}

{% block content %}
<center>
    <h1>Check out the Materials and Videos out there!!!</h1>
    
    <div class="row">
        <div class="col-sm-4">
        <video width="320" height="240" controls>
            <source src="" type="video/mp4">
        </video>
        </div>

        <div class="col-sm-4">
            <video width="320" height="240" controls>
                <source src="" type="video/mp4">
            </video>
        </div>

        <div class="col-sm-4">
            <video width="320" height="240" controls>
                <source src="" type="video/mp4">
            </video>
            </div>
    </div>
    <br>
    
    <h2>Find out the download Links..</h2>
    <h3>www.google.com</h3>
    <h3>www.youtube.com</h3>
    <br>
    <br>
    
    <button type="button" class="btn btn-primary">Click for Assessment</button>
    </center>
{% endblock %}


  

LAHI/teachers/templates/teachers/agenda.html
{% extends 'base.html' %}

{% block content %}
    <center>
    <h1>Check out the weekly updates!!!</h1>
    <br>
    <br>
<div class="container">
  <div class="card bg-success text-white">
    <a href="{% url 'teachers:upload_files' %}"><div class="card-body"><center><h1>Monday</h1></center></div></a>
  </div>
  <br>
  <div class="card bg-success text-white">
    <a href="{% url 'teachers:upload_files' %}"><div class="card-body"><center><h1>Tuesday</h1></center></div></a>
  </div>
  <br>
  <div class="card bg-success text-white">
    <a href="{% url 'teachers:upload_files' %}"><div class="card-body"><center><h1>Wednesday</h1></center></div></a>
  </div>
  <br>
  <div class="card bg-success text-white">
    <a href="{% url 'teachers:upload_files' %}"><div class="card-body"><center><h1>Thursday</h1></center></div></a>
  </div>
  <br>
  <div class="card bg-success text-white">
    <a href="{% url 'teachers:upload_files' %}"><div class="card-body"><center><h1>Friday</h1></center></div></a>
  </div>
  <br>
  <div class="card bg-success text-white">
    <a href="{% url 'teachers:upload_files' %}"><div class="card-body"><center><h1>Saturdays</h1></center></div></a>
  </div>
  
</div>
<center>
  {% endblock %}

LAHI/teachers/templates/teachers/class.html
<html>
    <head>
        <meta charset="utf-8">
        <title>Teacher Dashboard</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="css/class.css">
    </head>
    <body >
        <nav class="navbar navbar-light bg-primary">
            <a class="navbar-brand" href="#">{{ class }}</a>
            <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button> -->
            <!-- <div class="collapse navbar-collapse" id="navbarNav"> -->
              <!-- <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="/logout">Logout <span class="sr-only">(current)</span></a>
                </li>
              </ul> -->
            <!-- </div> -->
          </nav>
          <!-- <ul class="list-group">
            <li class="list-group-item">
                    {% for student in student_list %}
                    <li class="list-group-item">{{ student.name }}</li>
                    {% endfor %}</li>
          </ul> -->



        <button class="feedback" onclick="location.href='teacher_dashboard.html';">Back to Dashboard</button>

<!--Accordion wrapper-->
<div class="accordion md-accordion" id="accordionEx" role="tablist" aria-multiselectable="true">

    <!-- Accordion card -->
    <div class="card">
  
      <!-- Card header -->
      <div class="card-header" role="tab" id="headingOne1">
        <a data-toggle="collapse" data-parent="#accordionEx" href="#collapseOne1" aria-expanded="true"
          aria-controls="collapseOne1">
          <h5 class="mb-0">
            List of Students Enrolled <i class="fas fa-angle-down rotate-icon"></i>
          </h5>
        </a>
      </div>
  
      <!-- Card body -->
      <div id="collapseOne1" class="collapse show" role="tabpanel" aria-labelledby="headingOne1"
        data-parent="#accordionEx">
        <div class="card-body">
            <div class="form-group">
                <!-- <h5> List of Student enrolled </h5> -->
                <!-- <label for="student_list"> List of Student enrolled </label> -->
                <select multiple class="form-control" id="student_list">
                  {% for student in student_list %}
                    <option>{{ student.name }}</option>
                  {% endfor %} 
                </select>
              </div>
            </div>
      </div>
  
    </div>
    <!-- Accordion card -->
  
    <!-- Accordion card -->
    <div class="card">
  
      <!-- Card header -->
      <div class="card-header" role="tab" id="headingTwo2">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseTwo2"
          aria-expanded="false" aria-controls="collapseTwo2">
          <h5 class="mb-0">
            Add or Delete a Student <i class="fas fa-angle-down rotate-icon"></i>
          </h5>
        </a>
      </div>
  
      <!-- Card body -->
      <!-- <div id="collapseTwo2" class="collapse" role="tabpanel" aria-labelledby="headingTwo2"
        data-parent="#accordionEx"> -->
        <div class="card">
        <div class="card-body">
            <h5>Add a Student</h5>
            <form action="class.html" method="post" >
                <div class="form-group">
                    <label for="student_name">Student Name</label>
                    <input type="text" class="form-control" id="student_name" name = "student_name" required >
                  </div>
                  <div class="form-group">
                    <label for="roll_no">Roll No</label>
                    <input type="text" class="form-control" id="roll_no" name = "roll_no" required>
                  </div>
                  <div class="form-group">
                    <label for="mobile">Mobile</label>
                    <input type="text" class="form-control" id="Mobile" name = "mobile" required>
                  </div>
                  <div class="form-group">
                    <label for="PassWord">Password</label>
                    <input type="text" class="form-control" id="PassWord" name = "Password" required >
                  </div>
                <button type="submit" class="btn btn-primary"> Add Student </button>
              </form>
            
             
            <h5>Delete Student</h5>
            <form action = "class.html" method="post" >
                <div class="form-group">
                    <div class="form-group">
                        <select class="form-control" id="student" name = "student">
                            {% for student in student_list %}
                            <option>{{ student.name }}</option>
                            {% endfor %} 
                        </select>
                      </div>
                  </div>
                <button type="submit" class="btn btn-primary"> Delete Student </button>
              </form>
        </div>
      </div>
  
    </div>
    <!-- Accordion card -->
  
    <!-- Accordion card -->
    <div class="card">
  
      <!-- Card header -->
      <div class="card-header" role="tab" id="headingThree3">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseThree3"
          aria-expanded="false" aria-controls="collapseThree3">
          <h5 class="mb-0">
            Manage Weekly Agenda <i class="fas fa-angle-down rotate-icon"></i>
          </h5>
        </a>
      </div>
  
      <!-- Card body -->
      <div id="collapseThree3" class="collapse" role="tabpanel" aria-labelledby="headingThree3"
        data-parent="#accordionEx">
        <div class="card-body">
            <!-- <h5>Weekly Agenda</h5> -->
            <form action = "weekly_agenda.html" method="post" >
                <div class="form-group">
                    <label for="class">Class</label>
                    <input type="text" class="form-control" id="class" name = "class" placeholder="7" required>
                  </div>
                <div class="form-group">
                    <label for="Subject">Subject</label>
                    <input type="text" class="form-control" id="subject" name = "subject" placeholder="Math" required>
                </div>
                <button type="submit" class="btn btn-primary"> Manage Weekly Agenda </button>
            </form>
        </div>
      </div>
  
    </div>
    <!-- Accordion card -->
        <!-- Accordion card -->
        <div class="card">
  
            <!-- Card header -->
            <div class="card-header" role="tab" id="headingThree4">
              <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseThree4"
                aria-expanded="false" aria-controls="collapseThree4">
                <h5 class="mb-0">
                  Upload Content <i class="fas fa-angle-down rotate-icon"></i>
                </h5>
              </a>
            </div>
        
            <!-- Card body -->
            <div id="collapseThree4" class="collapse" role="tabpanel" aria-labelledby="headingThree4"
              data-parent="#accordionEx">
              <div class="card-body">
                <!-- <h5>Upload Content</h5> -->
                <form action = "class.html" method="post" >
                    <div class="form-group">
                        <label for="class">Class</label>
                        <input type="text" class="form-control" id="class" name = "class" placeholder="7" required>
                      </div>
                    <div class="form-group">
                        <label for="Subject">Subject</label>
                        <input type="text" class="form-control" id="subject" name = "subject" placeholder="Math" required>
                    </div>
                    <div class="form-group">
                        <label for="Topic">Topic</label>
                        <input type="text" class="form-control" id="topic" name = "topic" placeholder="Algebra" required>
                      </div>
                    <div class="form-group">
                      <label for="file">Select file</label>
                      <input type="file" class="form-control-file" id="file" name = "file" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Upload Content</button>
                  </form>
              </div>
            </div>
        
          </div>

          <div class="card">
  
            <!-- Card header -->
            <div class="card-header" role="tab" id="headingThree5">
              <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseThree5"
                aria-expanded="false" aria-controls="collapseThree5">
                <h5 class="mb-0">
                  Upload Assignments <i class="fas fa-angle-down rotate-icon"></i>
                </h5>
              </a>
            </div>
        
            <!-- Card body -->
            <div id="collapseThree5" class="collapse" role="tabpanel" aria-labelledby="headingThree5"
              data-parent="#accordionEx">
              <div class="card-body">
                <!-- <h5>Add Assignments</h5> -->
                <form action = "class.html" method="post" >
                    <div class="form-group">
                        <label for="class">Class</label>
                        <input type="text" class="form-control" id="class" name = "class" placeholder="7" required>
                      </div>
                    <div class="form-group">
                        <label for="Subject">Subject</label>
                        <input type="text" class="form-control" id="subject" name = "subject" placeholder="Math" required>
                    </div>
                    <div class="form-group">
                      <label for="file">Select file(.pdf or .docs)</label>
                      <input type="file" class="form-control-file" id="file" name = "file" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Upload Assignments</button>
                </form>
              </div>
            </div>
        
          </div>
  
  </div>
  <!-- Accordion wrapper -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
</html>



        



          

          <!-- <a class="nav-link" href="#item-1">Item 1</a> -->
    </body>
</html>

LAHI/teachers/templates/teachers/content.html
{% extends 'base.html' %}

{% block content %}

<!-- <div> -->
	<!-- <label for="content_type">Content Type</label>
                              <select class="form-control content-type" id="content" name = "content">
								<option>video</option>
								<option>audio</option>
								<option>image</option>
                             </select> -->
<!-- </div> -->

<div class="row">
	<center><h1>Materials for Day!!!</h1></center>
	{% for m in media %}
		<div class="col-sm-4">
			<video width="320" height="240" controls>
				<source src="/media/{{m.media}}" type="video/mp4">
			</video>
			
			<!-- <audio controls>
				<source src="/media/{{m.media}}" type="audio/ogg">
			</audio> -->

			<h3>{{ m.subject }}</h3>
			<p>{{ m.std }}</p>
			<p>{{ m.file_type }}</p>
			<form action="{% url 'main:download' m.media %}" method="post">
				{% csrf_token %}
				<button type="submit">
					download
				</button>
			</form>
			<!-- <a href="{{ m.media.url }}" download>Download</a> -->
			<a href="https://web.whatsapp.com/send?text={{request.META.HTTP_HOST}}/download/{{m.media}}">Share on whatsapp</a>
        </div>
	{% endfor %}
</div>
{% endblock %}

LAHI/teachers/templates/teachers/createstudent.html
{% extends 'base.html' %}

{% block content %}

    {% if error %}
    {{error}}
    {% endif %}
    <!-- <form action="{% url 'teachers:create_student' %}" method="post">
        {% csrf_token %}
        <input type="text" name="uname" placeholder="Username">
        <input type="password" name="pass" placeholder="Password">
        <input type="password" name="passagain" placeholder="confirm Password">
        <input type="number" name="rollno" placeholder="Roll number">
        <input type="number" name="phone" placeholder="Phone">
        <input type="text" name="std" placeholder="Class">
        <button type="submit">Submit</button>
    </form> -->
    <br><center><h1><b>Add Student to the class!!!</b></h1></center>
    <br><br><br><br>
    <div class="card-body">
        <!-- <h5>Add Assignments</h5> -->
        <form action ="{% url 'teachers:create_student' %}" method="post" >
            {% csrf_token %}
            <div class="form-group">
                <label for="Username" style="margin-left:18%">Username</label>
                <input type="text" style="width:60% ; margin-left:18%" class="form-control student-value" id="class" name = "uname" placeholder="Username" required>
              </div>
            <div class="form-group">
<<<<<<< HEAD
                <label for="Password" style="margin-left:18%">Password</label>
                <input type="password" style="width:60% ; margin-left:18%" class="form-control" id="password" name = "password" placeholder="Password" required>
=======
                <label for="Password">Password</label>
                <input type="password" class="form-control" id="password" name = "pass" placeholder="Password" required>
>>>>>>> 6ee8338b8e0759e15ff94347d0c00f7a9e212c37
            </div>
            <div class="form-group">
                <label for="confirm" style="margin-left:18%">Confirm Password</label>
                <input type="password" style="width:60% ; margin-left:18%" class="form-control" id="confirm password" name = "passagain" placeholder=" Confirm Password" required>
            </div>

            <div class="form-group ">
                <label for="rollno" style="margin-left:18%">Roll No.</label>
                <input type="number" style="width:60% ; margin-left:18%" class="form-control" id="rollno" name = "rollno" placeholder="Roll Number" required>
            </div>

            <div class="form-group mx-sm-3 mb-2">
                <label for="phone" style="margin-left:18%">Phone</label>
                <input type="number" style="width:60% ; margin-left:18%" class="form-control" id="phone" name = "phone" placeholder="Phone" required>
            </div>
            <div class="form-group">
                <label for="text" style="margin-left:18%">Class</label>
                <input type="text" style="width:60% ; margin-left:18%" class="form-control" id="class" name = "std" placeholder="Class" required>
            </div>

            <button type="submit" class="btn btn-primary">Add Student</button>
        </form>
      </div>
    
{% endblock %}

LAHI/teachers/templates/teachers/dashboard.html
{% extends 'base.html' %}

{% block content %}
    <center>
    <h1>Welcome {{ request.user }}</h1>
    <br>
    <br>
<div class="container">
  <div class="card bg-success text-white">
    <a href="{% url 'teachers:agenda' %}"><div class="card-body"><center><h1>Add Weekly-Schedule</h1></center></div></a>
  </div>
  <br>
  <div class="card bg-success text-white">
    <a href="{% url 'teachers:create_student' %}"><div class="card-body"><center><h1>Add Students</h1></center></div></a>
  </div>
  <br>
  <div class="card bg-success text-white">
    <a href="{% url 'teachers:materials' %}"><div class="card-body"><center><h1>Materials</h1></center></div></a>
  </div>
  <br>
  <div class="card bg-success text-white">
    <a href="#"><div class="card-body"><center><h1>Track Progress</h1></center></div></a>
  </div>
  <br>
  <div class="card bg-success text-white">
    <a href="#"><div class="card-body"><center><h1>Feedback</h1></center></div></a>
  </div>

  
</div>
<center>
  {% endblock %}

LAHI/teachers/templates/teachers/dashboard_test.html
<html>
    <head>
        <meta charset="utf-8">
        <title>Teacher Dashboard</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="css/teacher_dashboard.css">
    </head>
    <body>
        <nav class="navbar navbar-light bg-primary">
            <a class="navbar-brand" href="#">{{ teacher_name }}</a>
            <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button> -->
            <!-- <div class="collapse navbar-collapse" id="navbarNav"> -->
              <!-- <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="/logout">Logout <span class="sr-only">(current)</span></a>
                </li>
              </ul> -->
            <!-- </div> -->
          </nav>



        
        <div class = "class-parent">
          <div class="class-child">
            <ul class="list-inline">
                {% for class in class_list %}
                <!-- <a class="nav-link" href="class.html">{{ class }}</a> -->
                <button type="button" class="btn btn-primary btn-lg" onclick="location.href='class.html';">{{ class }}</button>
                <!-- <div class="btn-group btn-group-lg" role="group" aria-label="...">Right</div> -->
                <!-- <li class="list-inline-item"><button type="button" class="btn btn-outline-primary">{{ class }}</button> -->
                <!-- </li> -->
                <!-- <li>{{ athlete.name }}</li> -->
                {% endfor %}
              </ul>
              
          </div>
        </div>  
         





          
    </body>
</html>

LAHI/teachers/templates/teachers/deletestudent.html
{% extends 'base.html' %}

{% block content %}

<div class="card">
    <div class="card-body">
        <h2 class="text-center mt-3">Delete Student</h2>
        <form method="post" >
          <div class="form-group">
            <label for="Roll No">Roll No</label>
            <input type="number" class="form-control" id="Roll NO" name = "rollno" required >
          </div>
            <button type="submit" class="btn btn-primary"> Delete Student </button>
          </form>
        
         
        <!-- <h5>Delete Student</h5>
        <form method="post" >
            <div class="form-group">
                <div class="form-group">
                    <select class="form-control" id="student" name = "student">
                        {% for student in student_list %}
                        <option>{{ student.name }}</option>
                        {% endfor %} 
                    </select>
                  </div>
              </div>
            <button type="submit" class="btn btn-primary"> Delete Student </button>
          </form> -->
    </div>
  </div>
    
{% endblock %}

LAHI/teachers/templates/teachers/login.html
{% load static %}

<head>
        <meta charset="utf-8">
        <title>Djangonauts</title>
		<link rel="stylesheet" href="{% static 'css/styles.css' %}">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
</head>

{% block content %}
<div class="container myCtn">
	<div class="card">
		<div class="card-body">
			<div class="col-md-12">
				<h2 class="text-center mt-3">Sign in</h2>
					<form method="POST" class="main-form needs-validation" id="contact-form">
						{% csrf_token %}
						{{ form.as_p }}
						<button type="submit" value="Login" class="btn btn-primary mt-3 mx-auto">Submit</button>
					</form>
			</div>
        </div>
    </div>
</div>
{% endblock %}

LAHI/teachers/templates/teachers/teacher_tabs.html
{% extends 'base.html' %}

{% block content %}


<div id="list-example" class="list-group ">
    <a class="list-group-item list-group-item-action" href="http://127.0.0.1:8000/teacher/createstudent">ADD STUDENT</a>
    <a class="list-group-item list-group-item-action" href="http://127.0.0.1:8000/teacher/uploadfiles">UPLOAD FILES</a>
    <a class="list-group-item list-group-item-action" href="#list-item-3">Item 3</a>
    <a class="list-group-item list-group-item-action" href="#list-item-4">Item 4</a>
  </div>
  
    
{% endblock %}

LAHI/teachers/templates/teachers/uploadfiles.html
{% extends 'base.html' %}

{% block content %}
	 
<body>
	>
	<br><br><br><br><br><br><br>
	
	<div class="container">
		<div class="card">
			<div class="card-body">
				<div class="col-lg-12">
					<h1 class="text-center mt-3">Upload Files</h1>
					<br><br><br><br><br>
						<form method="POST" enctype="multipart/form-data" action="{% url 'teachers:upload_files' %}" class="main-form needs-validation" id="contact-form">
							{% csrf_token %}
							{{ form.as_p }}
							<br><br>
							<button type="submit" class="btn btn-primary"><center>Upload Content</center></button><br><br>
						</form>
				</div>
			</div>
		</div>
	</div>
	</body>

    <!-- <div class = "card text-centre">
		<div class = "card-body text-centre">
			<h4>Upload Files</h4>
			<form method="post" >
				{% csrf_token %}
				{{ form.as_p }}
				
			  </form>

		</div>
	</div> -->



{% endblock %}