LAHI/LAHI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('teacher/', include('teachers.urls')),
    path('student/', include('students.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LAHI/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
	path('', views.homepage, name='homepage'),
	path('download/<str:filename>', views.download, name='download'),
	path('logout', views.logout_view, name='logout')
]

LAHI/students/urls.py
from django.urls import path
from . import views 

app_name = 'students'

urlpatterns = [
	path('login', views.student_login, name='student_login'),
	path('materials', views.materials, name='materials'),
	path('dashboard', views.dashboard, name='dashboard'),
	path('agenda', views.agenda, name='agenda'),
	path('feedback',views.feedback, name='feedback'),
	path('content',views.content, name='content'),
]

LAHI/students/models.py
from django.db import models

# Create your models here.

LAHI/students/forms.py
from django import forms
from teachers.models import Student

class StudentAuthenticationForm(forms.ModelForm):
    pass
    # class Meta:
    #     model = Student
    #     fields = ['name', 'roll_no', 'phone']

LAHI/students/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.http import HttpResponse
from .forms import StudentAuthenticationForm
from django.contrib.auth.models import User
from teachers.models import Student
from main.models import MediaFile


def student_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            # if 'next' in request.POST:
            return redirect('students:dashboard')
            # else:
                # return redirect('articles:list')
                
    else:
        form = AuthenticationForm()
    return render(request, 'students/login.html', { 'form': form })
    # return HttpResponse("Student login")

def materials(request):
    media = MediaFile.objects.all()
    return render(request, 'students/test.html', {'media':media})

def dashboard(request):
    return render(request, 'students/dashboard.html')

def agenda(request):
    return render(request, 'students/agenda.html')

def feedback(request):
    return render(request, 'students/feedback.html')    
 
def content(request):
    return render(request, 'students/feedback.html') 

LAHI/students/templates/students/agenda.html
{% extends 'base.html' %}

{% block content %}
    <center>
    <h1>Check out the weekly updates!!!</h1>
    <br>
    <br>
<div class="container">
  <div class="card bg-success text-white">
    <a href="{% url 'students:materials' %}"><div class="card-body"><center><h1>Monday</h1></center></div></a>
  </div>
  <br>
  <div class="card bg-success text-white">
    <a href="{% url 'students:materials' %}"><div class="card-body"><center><h1>Tuesday</h1></center></div></a>
  </div>
  <br>
  <div class="card bg-success text-white">
    <a href="{% url 'students:materials' %}"><div class="card-body"><center><h1>Wednesday</h1></center></div></a>
  </div>
  <br>
  <div class="card bg-success text-white">
    <a href="{% url 'students:materials' %}"><div class="card-body"><center><h1>Thursday</h1></center></div></a>
  </div>
  <br>
  <div class="card bg-success text-white">
    <a href="{% url 'students:materials' %}"><div class="card-body"><center><h1>Friday</h1></center></div></a>
  </div>
  <br>
  <div class="card bg-success text-white">
    <a href="{% url 'students:materials' %}"><div class="card-body"><center><h1>Saturdays</h1></center></div></a>
  </div>
  
</div>
<center>
  {% endblock %}

LAHI/students/templates/students/dashboard.html
{% extends 'base.html' %}

{% block content %}
    <center>
    <h1>Welcome {{request.user}}</h1>
    <br>
    <br>
  <div class="container">
  <div class="card bg-info text-white">
    <a href="{% url 'students:agenda' %}"><div class="card-body"><center><h1>Weekly-Schedule</h1></center></div></a>
  </div>
  <br>
  <div class="card bg-info text-white">
    <a href="#"><div class="card-body"><center><h1>Test Results</h1></center></div></a>
  </div>
  <br>
  <div class="card bg-info text-white">
    <a href="{% url 'students:feedback' %}"><div class="card-body"><center><h1>FeedBack</h1></center></div></a>
  </div>
</div>
<center>

  {% endblock %}  
  

LAHI/students/templates/students/feedback.html
<!DOCTYPE html>    
<html>    
<head>    
<meta name="viewport" content="width=device-width, initial-scale=1">    
<style>    
* {    
  box-sizing: border-box;    
}    
    
input[type=text], select, textarea {    
  width: 100%;    
  padding: 12px;    
  border: 1px solid rgb(70, 68, 68);    
  border-radius: 4px;    
  resize: vertical;    
}    
input[type=email], select, textarea {    
  width: 100%;    
  padding: 12px;    
  border: 1px solid rgb(70, 68, 68);    
  border-radius: 4px;    
  resize: vertical;    
}    
    
label {    
  padding: 12px 12px 12px 0;    
  display: inline-block;    
}    
    
input[type=submit] {    
  background-color: rgb(37, 116, 161);    
  color: white;    
  padding: 12px 20px;    
  border: none;    
  border-radius: 4px;    
  cursor: pointer;    
  float: right;    
}    
    
input[type=submit]:hover {    
  background-color: #45a049;    
}    
    
.container {    
  border-radius: 5px;    
  background-color: #f2f2f2;    
  padding: 20px;    
}    
    
.col-25 {    
  float: left;    
  width: 25%;    
  margin-top: 6px;    
}    
    
.col-75 {    
  float: left;    
  width: 75%;    
  margin-top: 6px;    
}    
    
/* Clear floats after the columns */    
.row:after {    
  content: "";    
  display: table;    
  clear: both;    
}    
    
/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */    
</style>    
</head>    
<body>    
<h2>FEED BACK FORM</h2>    
<div class="container">    
  <form>    
    <div class="row">    
      <div class="col-25">    
        <label for="fname">First Name</label>    
      </div>    
      <div class="col-75">    
        <input type="text" id="fname" name="firstname" placeholder="Your name..">    
      </div>    
    </div>    
    <div class="row">    
      <div class="col-25">    
        <label for="lname">Last Name</label>    
      </div>    
      <div class="col-75">    
        <input type="text" id="lname" name="lastname" placeholder="Your last name..">    
      </div>    
    </div>    
    <div class="row">    
        <div class="col-25">    
          <label for="email">Mail Id</label>    
        </div>    
        <div class="col-75">    
          <input type="email" id="email" name="mailid" placeholder="Your mail id..">    
        </div>    
      </div>    
    
    <div class="row">    
      <div class="col-25">    
        <label for="feed_back">Feed Back</label>    
      </div>    
      <div class="col-75">    
        <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>    
      </div>    
    </div>    
    <div class="row">    
      <input type="submit" value="Submit">    
    </div>    
  </form>    
</div>    
    
</body>    
</html>    

LAHI/students/templates/students/login.html
{% load static %}

<head>
        <meta charset="utf-8">
        <title>Djangonauts</title>
		<link rel="stylesheet" href="{% static 'css/styles.css' %}">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
</head>

{% block content %}
<body>
<div class="container myCtn">
	<div class="card">
		<div class="card-body">
			<div class="col-md-12">
				<h2 class="text-center mt-3" class="main-form needs-validation" id="contact-form">Sign in</h2>
					<form method="POST">
						{% csrf_token %}
						{{ form.as_p }}
						<button type="submit" value="Login" class="btn btn-primary mt-3 mx-auto">Submit</button>
					</form>
			</div>
		</div>
	</div>
</div>
</body>

{% endblock %}

LAHI/students/templates/students/test.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    
	{% for m in media %}
		<div class="col-sm-4">
			<video width="320" height="240" controls>
				<source src="/media/{{m.media}}" type="video/mp4">
			</video>
			
			<!-- <audio controls>
				<source src="/media/{{m.media}}" type="audio/ogg">
			</audio> -->

			<h3>{{ m.subject }}</h3>
			<p>{{ m.std }}</p>
			<p>{{ m.file_type }}</p>
			<form action="{% url 'main:download' m.media %}" method="post">
				{% csrf_token %}
				<button type="submit">
					download
				</button>
			</form>
			<!-- <a href="{{ m.media.url }}" download>Download</a> -->
			<a href="https://web.whatsapp.com/send?text={{request.META.HTTP_HOST}}/download/{{m.media}}">Share on whatsapp</a>
        </div>
	{% endfor %}
</div>
{% endblock %}